import './style.css';
import {attributes,skills,progression,ranks,conditions,backgrounds,affiliations,gmTables} from './data/rules.js';
const KEY='semideuses-rpg-v01';
const defaultChar={name:'',level:1,origin:'Semideus Grego',background:'',affiliation:'',path:'',hitDie:8,casting:'INT',attrs:{FOR:10,DES:10,CON:10,INT:10,SAB:10,CAR:10},skillProf:{},skillExpert:{},saveProf:{},currentHP:0,currentMP:0,favor:0,notes:''};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{mode:'player',character:defaultChar,campaign:{name:'Minha Campanha',tier:1,notes:''}};
const mod=v=>Math.floor((Number(v)-10)/2); const sign=n=>n>=0?`+${n}`:`${n}`;
const prof=l=>progression.find(x=>x.level===Number(l))?.prof||2;
const hpMax=c=>{const n=Number(c.level),con=mod(c.attrs.CON),avg={6:4,8:5,10:6,12:7}[Number(c.hitDie)]||5;return Math.max(1,Number(c.hitDie)+con+Math.max(0,n-1)*(avg+con));};
const mpMax=c=>{const n=Number(c.level),m=mod(c.attrs[c.casting]||10);return Math.max(0,6+m+Math.max(0,n-1)*(2+m));};
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function set(path,value){const parts=path.split('.');let o=state;for(let i=0;i<parts.length-1;i++)o=o[parts[i]];o[parts.at(-1)]=value;save();render();}
function roll(max){return Math.floor(Math.random()*max)+1;}
function playerView(){const c=state.character,bp=prof(c.level),pp=10+mod(c.attrs.SAB)+(c.skillExpert['Percepção']?bp*2:c.skillProf['Percepção']?bp:0);const level=progression.find(x=>x.level===Number(c.level));return `
<section class="hero"><div><small>FICHA DO HERÓI</small><h2>${c.name||'Novo Herói'}</h2><p>Nível ${c.level} · ${c.affiliation||'Filiação não escolhida'}</p></div><div class="circle">${c.name?.[0]?.toUpperCase()||'?'}</div></section>
<section class="stats"><div><b>${hpMax(c)}</b><span>PV Máx.</span></div><div><b>${mpMax(c)}</b><span>MP Máx.</span></div><div><b>${sign(bp)}</b><span>Prof.</span></div><div><b>${pp}</b><span>Percepção</span></div></section>
<div class="tabs"><button data-tab="sheet">Ficha</button><button data-tab="progress">Progressão</button><button data-tab="rules">Regras</button></div>
<section class="card"><h3>Identidade</h3><div class="grid">
<label>Nome<input data-path="character.name" value="${c.name}"></label><label>Nível<input type="number" min="1" max="20" data-path="character.level" value="${c.level}"></label>
<label>Origem<input data-path="character.origin" value="${c.origin}"></label><label>Antecedente<select data-path="character.background"><option value="">Escolha</option>${backgrounds.map(x=>`<option ${c.background===x.id?'selected':''} value="${x.id}">${x.name}</option>`).join('')}</select></label>
<label>Filiação<select data-path="character.affiliation"><option value="">Escolha</option>${affiliations.map(x=>`<option ${c.affiliation===x.id?'selected':''} value="${x.id}">${x.name} (${x.status})</option>`).join('')}</select></label><label>Caminho Divino<input data-path="character.path" value="${c.path}"></label>
<label>Dado de Vida<select data-path="character.hitDie">${[6,8,10,12].map(x=>`<option ${Number(c.hitDie)===x?'selected':''} value="${x}">d${x}</option>`).join('')}</select></label><label>Atributo de Conjuração<select data-path="character.casting">${attributes.map(x=>`<option ${c.casting===x?'selected':''}>${x}</option>`).join('')}</select></label>
</div></section>
<section class="card"><h3>Atributos</h3><div class="attribute-grid">${attributes.map(a=>`<label><span>${a}</span><input type="number" min="1" max="30" data-path="character.attrs.${a}" value="${c.attrs[a]}"><b>${sign(mod(c.attrs[a]))}</b></label>`).join('')}</div></section>
<section class="card"><h3>Perícias</h3>${skills.map(([n,a])=>{let v=mod(c.attrs[a])+(c.skillExpert[n]?bp*2:c.skillProf[n]?bp:0);return `<div class="skill"><span>${n} <small>${a}</small></span><label>P<input type="checkbox" data-check="prof|${n}" ${c.skillProf[n]?'checked':''}></label><label>E<input type="checkbox" data-check="expert|${n}" ${c.skillExpert[n]?'checked':''}></label><b>${sign(v)}</b></div>`}).join('')}</section>
<section class="card"><h3>Este nível concede</h3><ul>${level.gains.map(g=>`<li>${g}</li>`).join('')}</ul></section>
<section class="card"><h3>Condições</h3><div class="chips">${conditions.map(x=>`<button>${x}</button>`).join('')}</div></section>
<section class="card"><h3>Notas e poderes</h3><textarea data-path="character.notes">${c.notes}</textarea></section>`;}
function masterView(){return `<section class="hero"><div><small>PAINEL DO MESTRE</small><h2>${state.campaign.name}</h2><p>Ferramentas móveis de sessão</p></div><div class="circle">M</div></section>
<section class="card"><h3>Campanha</h3><div class="grid"><label>Nome<input data-path="campaign.name" value="${state.campaign.name}"></label><label>Tier<input type="number" min="1" max="4" data-path="campaign.tier" value="${state.campaign.tier}"></label></div><textarea data-path="campaign.notes">${state.campaign.notes}</textarea></section>
<section class="card"><h3>Rolador rápido</h3><div class="dice">${[4,6,8,10,12,20,100].map(d=>`<button data-roll="${d}">d${d}</button>`).join('')}</div><div id="rollResult" class="result">Toque em um dado</div></section>
<section class="card"><h3>Manipulação da Névoa</h3>${gmTables.mist.map(x=>`<div class="row"><b>${x.complexity}</b><span>CD ${x.dc}</span><small>${x.example}</small></div>`).join('')}</section>
<section class="card"><h3>Complicação de missão</h3><button class="primary" id="missionRoll">Rolar 1d10</button><div id="missionResult" class="result"></div></section>
<section class="card"><h3>Reação de NPC</h3><button class="primary" id="npcRoll">Rolar 1d6</button><div id="npcResult" class="result"></div></section>
<section class="card"><h3>Banco do Mestre</h3><p class="warning">Estrutura pronta. Bestiário, atlas, facções, vilões, tesouros e encontros serão inseridos por módulos conforme a catalogação oficial dos livros.</p></section>`;}
function render(){document.querySelector('#app').innerHTML=`<header><div><h1>Semideuses RPG 3e</h1><small>Compêndio móvel oficial da mesa</small></div><button id="mode">${state.mode==='player'?'Modo Mestre':'Modo Jogador'}</button></header><main>${state.mode==='player'?playerView():masterView()}</main><footer><button id="export">Exportar backup</button><button id="install">Instalar</button></footer>`;bind();}
function bind(){document.querySelector('#mode').onclick=()=>{state.mode=state.mode==='player'?'master':'player';save();render();};document.querySelectorAll('[data-path]').forEach(el=>{el.onchange=e=>set(el.dataset.path,el.type==='number'?Number(el.value):el.value);});document.querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{const [type,n]=el.dataset.check.split('|');if(type==='prof')state.character.skillProf[n]=el.checked;else state.character.skillExpert[n]=el.checked;save();render();});document.querySelectorAll('[data-roll]').forEach(b=>b.onclick=()=>document.querySelector('#rollResult').textContent=`d${b.dataset.roll}: ${roll(Number(b.dataset.roll))}`);const m=document.querySelector('#missionRoll');if(m)m.onclick=()=>{const r=roll(10);document.querySelector('#missionResult').textContent=`${r}. ${gmTables.missionComplications[r-1]}`};const n=document.querySelector('#npcRoll');if(n)n.onclick=()=>{const r=roll(6);document.querySelector('#npcResult').textContent=`${r}. ${gmTables.npcReaction[r-1]}`};document.querySelector('#export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='semideuses-backup.json';a.click();};document.querySelector('#install').onclick=()=>alert('Android: menu do navegador → Instalar app. iPhone: Safari → Compartilhar → Adicionar à Tela de Início.');}
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
